---
sudo: required
dist: trusty

language: python
python: "3.6"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.4.0.0
  - ANSIBLE_VERSION=2.3.0.0
  - ANSIBLE_VERSION=2.2.0.0
  - ANSIBLE_VERSION=2.1.0.0
before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip3 install ansible; else pip3 install ansible==$ANSIBLE_VERSION; fi
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml -e docker_version="18.02.0~ce-0~ubuntu" --syntax-check
  # Run the role/playbook with ansible-playbook.
  # dry run as we're not able to install this on travis side
  - ansible-playbook -i tests/inventory tests/test.yml -e docker_version="18.02.0~ce-0~ubuntu" --connection=local -b --check
  # Run the role/playbook again, checking to make sure it's idempotent.
  #- >
  #  ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  #  | grep -q 'changed=0.*failed=0'
  #  && (echo 'Idempotence test: pass' && exit 0)
  #  || (echo 'Idempotence test: fail' && exit 1)

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
