---
- name: Unlock docker apt version
  dpkg_selections:
    name: "{{ docker_package_name }}"
    selection: install
  changed_when: false
  become: yes

- name: Install gnupg-curl and python pip
  apt:
    name: "{{item}}"
    force: yes
  become: yes
  with_items:
  - gnupg-curl #required for for apt-key https support
  - python-pip

- name: Install docker-py
  pip:
    name: docker-py
    version : "{{dockerpy_version}}"
  become: yes

- name: Add docker apt repo
  apt_repository:
    repo: 'deb {{docker_repository_url}} {{ ansible_distribution_release }} edge'
    mode: 644
    state: present
  become: yes

- name: Import the Docker repository key
  apt_key:
    data: "{{lookup('file', 'docker.gpg')}}"
    id: F273FCD8
    state: present
    validate_certs: no
  become: yes

- name: update apt cache
  apt: update_cache=yes
  changed_when: false
  become: yes

- name: Install Docker package
  apt:
    name: "{{ docker_package_name }}={{ docker_version }}"
    force: "{{ docker_force_version }}"
  become: yes
  notify: Restart docker

- name: Install Docker-compose package
  apt:
    name: "{{ docker_compose_package_name }}={{ docker_compose_version }}"
    force: "{{ docker_force_version }}"
  become: yes
  
- name: Configure Docker bridge MTU
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "mtu": 1500
      }
  become: yes
  notify: Restart docker

- name: Lock docker apt version
  dpkg_selections:
    name: "{{ docker_package_name }}"
    selection: hold
  changed_when: false
  become: yes

- name: Create systemctl structure for docker
  file: path=/etc/systemd/system/docker.service.d state=directory
  become: yes

- name: Create a docker group
  group:
    name: docker
    state: present
  become: yes

- name: Start docker
  service: name=docker state=started
  become: yes

- name: Create registry certificate folder
  file: path=/etc/docker/certs.d/{{ item.url }}/ state=directory
  become: yes
  when: item.url != "index.docker.io"
  with_items: "{{ docker_registries }}"

- name: Install registry certificate
  copy:
    src: "{{item.certificate}}"
    dest: "/etc/docker/certs.d/{{ item.url }}/ca.crt"
  when: item.url != "index.docker.io" and item.certificate is defined
  with_items: "{{ docker_registries }}"

- name: Grab registry certificate
  shell: "echo |  openssl s_client -connect {{ item.url }}:{{item.port}} 2>/dev/null | openssl x509 -text > /etc/docker/certs.d/{{ item.url }}/ca.crt"
  when: item.url != "index.docker.io" and item.port is defined
  with_items: "{{ docker_registries }}"

- meta: flush_handlers
